import Head from "next/head";
import Image from "next/image";
import Section from "components/Section";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Yerba mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <h1 className="text-5xl text-center font-bold py-8">Home</h1>
      </Section>
    </div>
  );
}
